version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c 'sleep 3 && npm test'
    env_file:
      - ./app/.env.example
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: psqlbase