version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: ilyag96/hexlet-lvl1-project:latest
    environment:
      - ./.env
    depends_on:
      - db
    command: bash -c 'sleep 3 && npm test'

  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

volumes:
  pgdata: