version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c 'sleep 3 && npm test'
    volumes:
  #    - type: bind  unfortunately useless for hexlet checks :(
  #      source: ./app/.env.example
  #      target: /app/.env
      - ./app:/app
    environment:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres