FROM node:14.18.1-slim

RUN apt-get update && apt-get install -yq make && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm ci

COPY app/. .

EXPOSE 8080

CMD npm start