name: push

on: push

env:
  APP_IMAGE_NAME: ilyag96/ilyag96/hexlet-lvl1-project

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: —Åheck
        run: |
            docker-compose -f docker-compose.override.yaml up --abort-on-container-exit

      - name: push
        uses: docker/build-push-action@v2
        with:
          context: ./app
          file: Dockerfile.prod
          cache-from: type=registry,ref=${{ env.APP_IMAGE_NAME }}:cached
          push: true
          tags: ${{ env.APP_IMAGE_NAME }}:latest


